version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 5444312c000a7179385d94aa6c044a05a07c03b642c94124
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: 5444312c000a7179385d94aa6c044a05a07c03b642c94124

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: 4e54e3ad8968dabbcd3909dab75aff8147ad98d960170a99
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
